import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "pages_blocks_cta_cards" CASCADE;
  DROP TABLE "_pages_v_blocks_cta_cards" CASCADE;
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "enable_cards";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "enable_link";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "link_type";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "link_new_tab";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "link_url";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "link_label";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "link_appearance";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_card_block_cards" DROP COLUMN "orientation";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "enable_cards";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "enable_link";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "link_type";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "link_new_tab";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "link_url";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "link_label";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "link_appearance";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_card_block_cards" DROP COLUMN "orientation";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_cta_cards_color";
  DROP TYPE "public"."enum_pages_blocks_cta_cards_link_type";
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_type";
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_appearance";
  DROP TYPE "public"."enum_pages_blocks_content_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_content_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_content_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_content_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_content_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_content_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_card_block_cards_orientation";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_team_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_team_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_team_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_team_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_team_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_team_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_cta_cards_color";
  DROP TYPE "public"."enum__pages_v_blocks_cta_cards_link_type";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_type";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_appearance";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_cards_orientation";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_bottom_accent";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_cta_cards_color" AS ENUM('purple', 'coral', 'cyan');
  CREATE TYPE "public"."enum_pages_blocks_cta_cards_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_appearance" AS ENUM('brand', 'brandPlinth', 'default', 'primary', 'secondary', 'accent', 'neutral', 'success', 'outline');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_card_block_cards_orientation" AS ENUM('vertical', 'horizontal');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_cards_color" AS ENUM('purple', 'coral', 'cyan');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_cards_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_appearance" AS ENUM('brand', 'brandPlinth', 'default', 'primary', 'secondary', 'accent', 'neutral', 'success', 'outline');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_cards_orientation" AS ENUM('vertical', 'horizontal');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TABLE "pages_blocks_cta_cards" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title" varchar,
  	"body" varchar,
  	"color" "enum_pages_blocks_cta_cards_color" DEFAULT 'coral',
  	"with_link" boolean DEFAULT false,
  	"link_type" "enum_pages_blocks_cta_cards_link_type" DEFAULT 'reference',
  	"link_new_tab" boolean,
  	"link_url" varchar DEFAULT '#',
  	"link_label" varchar,
  	"background_image_id" integer,
  	"background_opacity" numeric DEFAULT 100
  );
  
  CREATE TABLE "_pages_v_blocks_cta_cards" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"title" varchar,
  	"body" varchar,
  	"color" "enum__pages_v_blocks_cta_cards_color" DEFAULT 'coral',
  	"with_link" boolean DEFAULT false,
  	"link_type" "enum__pages_v_blocks_cta_cards_link_type" DEFAULT 'reference',
  	"link_new_tab" boolean,
  	"link_url" varchar DEFAULT '#',
  	"link_label" varchar,
  	"background_image_id" integer,
  	"background_opacity" numeric DEFAULT 100,
  	"_uuid" varchar
  );
  
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "enable_cards" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "enable_link" boolean;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "link_type" "enum_pages_blocks_content_columns_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "link_url" varchar DEFAULT '#';
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "link_label" varchar;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "link_appearance" "enum_pages_blocks_content_columns_link_appearance" DEFAULT 'brand';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_content_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_top_bars" "enum_pages_blocks_content_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_top_accent" "enum_pages_blocks_content_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_content_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_content_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_content_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_media_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_top_bars" "enum_pages_blocks_media_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_top_accent" "enum_pages_blocks_media_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_media_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_media_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_media_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_archive_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_top_bars" "enum_pages_blocks_archive_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_top_accent" "enum_pages_blocks_archive_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_archive_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_archive_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_archive_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_form_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_top_bars" "enum_pages_blocks_form_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_top_accent" "enum_pages_blocks_form_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_form_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_form_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_form_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_card_block_cards" ADD COLUMN "orientation" "enum_pages_blocks_card_block_cards_orientation" DEFAULT 'vertical';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_card_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_top_bars" "enum_pages_blocks_card_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_top_accent" "enum_pages_blocks_card_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_card_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_card_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_card_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_carousel_logo_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_top_bars" "enum_pages_blocks_carousel_logo_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_top_accent" "enum_pages_blocks_carousel_logo_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_carousel_logo_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_carousel_logo_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_carousel_logo_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_static_map_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_top_bars" "enum_pages_blocks_static_map_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_top_accent" "enum_pages_blocks_static_map_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_static_map_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_static_map_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_static_map_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_team_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_top_bars" "enum_pages_blocks_team_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_top_accent" "enum_pages_blocks_team_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_team_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_team_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_team_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "enable_cards" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "enable_link" boolean;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "link_type" "enum__pages_v_blocks_content_columns_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "link_url" varchar DEFAULT '#';
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "link_label" varchar;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "link_appearance" "enum__pages_v_blocks_content_columns_link_appearance" DEFAULT 'brand';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_content_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_content_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_content_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_content_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_content_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_content_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_media_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_media_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_media_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_media_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_media_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_media_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_archive_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_archive_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_archive_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_archive_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_archive_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_archive_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_form_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_form_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_form_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_form_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_form_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_form_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_card_block_cards" ADD COLUMN "orientation" "enum__pages_v_blocks_card_block_cards_orientation" DEFAULT 'vertical';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_card_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_card_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_card_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_card_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_card_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_card_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_carousel_logo_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_carousel_logo_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_carousel_logo_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_carousel_logo_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_carousel_logo_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_carousel_logo_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_static_map_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_static_map_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_static_map_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_static_map_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_static_map_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_static_map_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_team_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_team_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_team_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_team_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_team_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_team_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_cta_cards" ADD CONSTRAINT "pages_blocks_cta_cards_background_image_id_media_id_fk" FOREIGN KEY ("background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_cta_cards" ADD CONSTRAINT "pages_blocks_cta_cards_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_cta"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_cta_cards" ADD CONSTRAINT "_pages_v_blocks_cta_cards_background_image_id_media_id_fk" FOREIGN KEY ("background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_cta_cards" ADD CONSTRAINT "_pages_v_blocks_cta_cards_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_cta"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "pages_blocks_cta_cards_order_idx" ON "pages_blocks_cta_cards" USING btree ("_order");
  CREATE INDEX "pages_blocks_cta_cards_parent_id_idx" ON "pages_blocks_cta_cards" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_cta_cards_background_image_idx" ON "pages_blocks_cta_cards" USING btree ("background_image_id");
  CREATE INDEX "_pages_v_blocks_cta_cards_order_idx" ON "_pages_v_blocks_cta_cards" USING btree ("_order");
  CREATE INDEX "_pages_v_blocks_cta_cards_parent_id_idx" ON "_pages_v_blocks_cta_cards" USING btree ("_parent_id");
  CREATE INDEX "_pages_v_blocks_cta_cards_background_image_idx" ON "_pages_v_blocks_cta_cards" USING btree ("background_image_id");`)
}
