import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_cta_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_cta_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_cta_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_cta_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_cta_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_cta_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_content_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_media_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_archive_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_form_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_card_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_static_map_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_timeline_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_timeline_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_timeline_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_timeline_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_timeline_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_timeline_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_team_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_content_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_timeline_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_timeline_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_timeline_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_timeline_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_timeline_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_timeline_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_top_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_top_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_top_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_bottom_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_bottom_bars" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_team_divider_bottom_accent" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  DROP TABLE "pages_blocks_divider" CASCADE;
  DROP TABLE "_pages_v_blocks_divider" CASCADE;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_cta_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_top_bars" "enum_pages_blocks_cta_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_top_accent" "enum_pages_blocks_cta_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_cta_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_cta_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_cta_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_content_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_top_bars" "enum_pages_blocks_content_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_top_accent" "enum_pages_blocks_content_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_content_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_content_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_content_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_media_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_top_bars" "enum_pages_blocks_media_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_top_accent" "enum_pages_blocks_media_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_media_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_media_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_media_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_archive_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_top_bars" "enum_pages_blocks_archive_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_top_accent" "enum_pages_blocks_archive_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_archive_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_archive_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_archive_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_form_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_top_bars" "enum_pages_blocks_form_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_top_accent" "enum_pages_blocks_form_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_form_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_form_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_form_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_card_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_top_bars" "enum_pages_blocks_card_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_top_accent" "enum_pages_blocks_card_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_card_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_card_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_card_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_carousel_logo_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_top_bars" "enum_pages_blocks_carousel_logo_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_top_accent" "enum_pages_blocks_carousel_logo_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_carousel_logo_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_carousel_logo_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_carousel_logo_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_static_map_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_top_bars" "enum_pages_blocks_static_map_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_top_accent" "enum_pages_blocks_static_map_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_static_map_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_static_map_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_static_map_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_timeline_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_top_bars" "enum_pages_blocks_timeline_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_top_accent" "enum_pages_blocks_timeline_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_timeline_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_timeline_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_timeline_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_top_pattern" "enum_pages_blocks_team_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_top_bars" "enum_pages_blocks_team_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_top_accent" "enum_pages_blocks_team_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_bottom_pattern" "enum_pages_blocks_team_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_bottom_bars" "enum_pages_blocks_team_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "pages_blocks_team" ADD COLUMN "divider_bottom_accent" "enum_pages_blocks_team_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_cta_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_cta_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_cta_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_cta_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_cta_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_cta_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_content_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_content_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_content_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_content_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_content_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_content_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_media_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_media_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_media_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_media_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_media_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_media_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_archive_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_archive_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_archive_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_archive_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_archive_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_archive_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_form_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_form_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_form_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_form_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_form_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_form_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_card_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_card_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_card_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_card_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_card_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_card_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_carousel_logo_block_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_carousel_logo_block_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_carousel_logo_block_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_carousel_logo_block_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_carousel_logo_block_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_carousel_logo_block_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_static_map_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_static_map_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_static_map_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_static_map_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_static_map_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_static_map_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_timeline_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_timeline_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_timeline_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_timeline_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_timeline_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_timeline_divider_bottom_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_top_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_top_pattern" "enum__pages_v_blocks_team_divider_top_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_top_bars" "enum__pages_v_blocks_team_divider_top_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_top_accent" "enum__pages_v_blocks_team_divider_top_accent" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_bottom_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_bottom_pattern" "enum__pages_v_blocks_team_divider_bottom_pattern" DEFAULT 'a';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_bottom_bars" "enum__pages_v_blocks_team_divider_bottom_bars" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "divider_bottom_accent" "enum__pages_v_blocks_team_divider_bottom_accent" DEFAULT 'default';
  DROP TYPE "public"."enum_pages_blocks_divider_pattern";
  DROP TYPE "public"."enum_pages_blocks_divider_primary_color";
  DROP TYPE "public"."enum_pages_blocks_divider_secondary_color";
  DROP TYPE "public"."enum__pages_v_blocks_divider_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_divider_primary_color";
  DROP TYPE "public"."enum__pages_v_blocks_divider_secondary_color";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_divider_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum_pages_blocks_divider_primary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum_pages_blocks_divider_secondary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_divider_pattern" AS ENUM('a', 'b', 'c', 'd');
  CREATE TYPE "public"."enum__pages_v_blocks_divider_primary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_divider_secondary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  CREATE TABLE "pages_blocks_divider" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"pattern" "enum_pages_blocks_divider_pattern" DEFAULT 'a',
  	"primary_color" "enum_pages_blocks_divider_primary_color" DEFAULT 'default',
  	"secondary_color" "enum_pages_blocks_divider_secondary_color" DEFAULT 'default',
  	"block_name" varchar
  );
  
  CREATE TABLE "_pages_v_blocks_divider" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"pattern" "enum__pages_v_blocks_divider_pattern" DEFAULT 'a',
  	"primary_color" "enum__pages_v_blocks_divider_primary_color" DEFAULT 'default',
  	"secondary_color" "enum__pages_v_blocks_divider_secondary_color" DEFAULT 'default',
  	"_uuid" varchar,
  	"block_name" varchar
  );
  
  ALTER TABLE "pages_blocks_divider" ADD CONSTRAINT "pages_blocks_divider_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_divider" ADD CONSTRAINT "_pages_v_blocks_divider_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "pages_blocks_divider_order_idx" ON "pages_blocks_divider" USING btree ("_order");
  CREATE INDEX "pages_blocks_divider_parent_id_idx" ON "pages_blocks_divider" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_divider_path_idx" ON "pages_blocks_divider" USING btree ("_path");
  CREATE INDEX "_pages_v_blocks_divider_order_idx" ON "_pages_v_blocks_divider" USING btree ("_order");
  CREATE INDEX "_pages_v_blocks_divider_parent_id_idx" ON "_pages_v_blocks_divider" USING btree ("_parent_id");
  CREATE INDEX "_pages_v_blocks_divider_path_idx" ON "_pages_v_blocks_divider" USING btree ("_path");
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "full_width";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_top_bars";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_top_accent";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "divider_bottom_accent";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "full_width";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_top_enabled";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_top_pattern";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_top_bars";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_top_accent";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_bottom_enabled";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_bottom_pattern";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_bottom_bars";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_cta_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_cta_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_cta_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_cta_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_cta_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_cta_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_content_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_content_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_content_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_content_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_content_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_content_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_media_block_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_archive_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_form_block_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_card_block_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_carousel_logo_block_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_static_map_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_timeline_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_timeline_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_timeline_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_timeline_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_timeline_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_timeline_divider_bottom_accent";
  DROP TYPE "public"."enum_pages_blocks_team_divider_top_pattern";
  DROP TYPE "public"."enum_pages_blocks_team_divider_top_bars";
  DROP TYPE "public"."enum_pages_blocks_team_divider_top_accent";
  DROP TYPE "public"."enum_pages_blocks_team_divider_bottom_pattern";
  DROP TYPE "public"."enum_pages_blocks_team_divider_bottom_bars";
  DROP TYPE "public"."enum_pages_blocks_team_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_cta_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_cta_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_cta_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_cta_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_cta_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_cta_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_content_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_archive_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_card_block_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_logo_block_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_static_map_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_timeline_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_timeline_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_timeline_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_timeline_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_timeline_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_timeline_divider_bottom_accent";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_top_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_top_bars";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_top_accent";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_bottom_pattern";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_bottom_bars";
  DROP TYPE "public"."enum__pages_v_blocks_team_divider_bottom_accent";`)
}
