import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Narrowing an enum is a drop-and-recreate, and the closing
 * `USING "col"::"enum"` cast aborts the whole migration on any row still holding
 * a value the new enum no longer lists. The UPDATEs added below run while each
 * column is temporarily `text` and rewrite those rows first.
 *
 * Surface colours lost `green`, so it becomes `purple` — the primary token.
 * Divider slots lost `pink`, `amber`, `white` and `ink`; those become `default`,
 * which restores the artwork's own hex rather than repainting it.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_content_columns_type" AS ENUM('text', 'media');
  CREATE TYPE "public"."enum_pages_blocks_content_columns_decorator_vertical_color" AS ENUM('purple', 'coral', 'cyan');
  CREATE TYPE "public"."enum_pages_blocks_content_columns_decorator_horizontal_color" AS ENUM('purple', 'coral', 'cyan');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_type" AS ENUM('text', 'media');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_decorator_vertical_color" AS ENUM('purple', 'coral', 'cyan');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_decorator_horizontal_color" AS ENUM('purple', 'coral', 'cyan');
  ALTER TABLE "pages_hero_slides" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "pages_hero_slides" ALTER COLUMN "color" SET DEFAULT 'purple'::text;
  UPDATE "pages_hero_slides" SET "color" = 'purple' WHERE "color" NOT IN ('purple', 'coral', 'cyan');
  DROP TYPE "public"."enum_pages_hero_slides_color";
  CREATE TYPE "public"."enum_pages_hero_slides_color" AS ENUM('purple', 'coral', 'cyan');
  ALTER TABLE "pages_hero_slides" ALTER COLUMN "color" SET DEFAULT 'purple'::"public"."enum_pages_hero_slides_color";
  ALTER TABLE "pages_hero_slides" ALTER COLUMN "color" SET DATA TYPE "public"."enum_pages_hero_slides_color" USING "color"::"public"."enum_pages_hero_slides_color";
  ALTER TABLE "pages_blocks_cta_cards" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::text;
  UPDATE "pages_blocks_cta_cards" SET "color" = 'purple' WHERE "color" NOT IN ('purple', 'coral', 'cyan');
  DROP TYPE "public"."enum_pages_blocks_cta_cards_color";
  CREATE TYPE "public"."enum_pages_blocks_cta_cards_color" AS ENUM('purple', 'coral', 'cyan');
  ALTER TABLE "pages_blocks_cta_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::"public"."enum_pages_blocks_cta_cards_color";
  ALTER TABLE "pages_blocks_cta_cards" ALTER COLUMN "color" SET DATA TYPE "public"."enum_pages_blocks_cta_cards_color" USING "color"::"public"."enum_pages_blocks_cta_cards_color";
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_cta_variant";
  CREATE TYPE "public"."enum_pages_blocks_cta_variant" AS ENUM('primary', 'secondary', 'background', 'highlight');
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_cta_variant" USING "variant"::"public"."enum_pages_blocks_cta_variant";
  ALTER TABLE "pages_blocks_card_block_cards" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_card_block_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::text;
  UPDATE "pages_blocks_card_block_cards" SET "color" = 'purple' WHERE "color" NOT IN ('purple', 'coral', 'cyan');
  DROP TYPE "public"."enum_pages_blocks_card_block_cards_color";
  CREATE TYPE "public"."enum_pages_blocks_card_block_cards_color" AS ENUM('purple', 'coral', 'cyan');
  ALTER TABLE "pages_blocks_card_block_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::"public"."enum_pages_blocks_card_block_cards_color";
  ALTER TABLE "pages_blocks_card_block_cards" ALTER COLUMN "color" SET DATA TYPE "public"."enum_pages_blocks_card_block_cards_color" USING "color"::"public"."enum_pages_blocks_card_block_cards_color";
  ALTER TABLE "pages_blocks_divider" ALTER COLUMN "primary_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_divider" ALTER COLUMN "primary_color" SET DEFAULT 'default'::text;
  UPDATE "pages_blocks_divider" SET "primary_color" = 'default' WHERE "primary_color" NOT IN ('default', 'purple', 'coral', 'cyan', 'green');
  DROP TYPE "public"."enum_pages_blocks_divider_primary_color";
  CREATE TYPE "public"."enum_pages_blocks_divider_primary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  ALTER TABLE "pages_blocks_divider" ALTER COLUMN "primary_color" SET DEFAULT 'default'::"public"."enum_pages_blocks_divider_primary_color";
  ALTER TABLE "pages_blocks_divider" ALTER COLUMN "primary_color" SET DATA TYPE "public"."enum_pages_blocks_divider_primary_color" USING "primary_color"::"public"."enum_pages_blocks_divider_primary_color";
  ALTER TABLE "pages_blocks_divider" ALTER COLUMN "secondary_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_divider" ALTER COLUMN "secondary_color" SET DEFAULT 'default'::text;
  UPDATE "pages_blocks_divider" SET "secondary_color" = 'default' WHERE "secondary_color" NOT IN ('default', 'purple', 'coral', 'cyan', 'green');
  DROP TYPE "public"."enum_pages_blocks_divider_secondary_color";
  CREATE TYPE "public"."enum_pages_blocks_divider_secondary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  ALTER TABLE "pages_blocks_divider" ALTER COLUMN "secondary_color" SET DEFAULT 'default'::"public"."enum_pages_blocks_divider_secondary_color";
  ALTER TABLE "pages_blocks_divider" ALTER COLUMN "secondary_color" SET DATA TYPE "public"."enum_pages_blocks_divider_secondary_color" USING "secondary_color"::"public"."enum_pages_blocks_divider_secondary_color";
  ALTER TABLE "pages" ALTER COLUMN "hero_bg_color" SET DATA TYPE text;
  ALTER TABLE "pages" ALTER COLUMN "hero_bg_color" SET DEFAULT 'base'::text;
  UPDATE "pages" SET "hero_bg_color" = 'purple' WHERE "hero_bg_color" NOT IN ('base', 'purple', 'coral', 'cyan');
  DROP TYPE "public"."enum_pages_hero_bg_color";
  CREATE TYPE "public"."enum_pages_hero_bg_color" AS ENUM('base', 'purple', 'coral', 'cyan');
  ALTER TABLE "pages" ALTER COLUMN "hero_bg_color" SET DEFAULT 'base'::"public"."enum_pages_hero_bg_color";
  ALTER TABLE "pages" ALTER COLUMN "hero_bg_color" SET DATA TYPE "public"."enum_pages_hero_bg_color" USING "hero_bg_color"::"public"."enum_pages_hero_bg_color";
  ALTER TABLE "_pages_v_version_hero_slides" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_version_hero_slides" ALTER COLUMN "color" SET DEFAULT 'purple'::text;
  UPDATE "_pages_v_version_hero_slides" SET "color" = 'purple' WHERE "color" NOT IN ('purple', 'coral', 'cyan');
  DROP TYPE "public"."enum__pages_v_version_hero_slides_color";
  CREATE TYPE "public"."enum__pages_v_version_hero_slides_color" AS ENUM('purple', 'coral', 'cyan');
  ALTER TABLE "_pages_v_version_hero_slides" ALTER COLUMN "color" SET DEFAULT 'purple'::"public"."enum__pages_v_version_hero_slides_color";
  ALTER TABLE "_pages_v_version_hero_slides" ALTER COLUMN "color" SET DATA TYPE "public"."enum__pages_v_version_hero_slides_color" USING "color"::"public"."enum__pages_v_version_hero_slides_color";
  ALTER TABLE "_pages_v_blocks_cta_cards" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::text;
  UPDATE "_pages_v_blocks_cta_cards" SET "color" = 'purple' WHERE "color" NOT IN ('purple', 'coral', 'cyan');
  DROP TYPE "public"."enum__pages_v_blocks_cta_cards_color";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_cards_color" AS ENUM('purple', 'coral', 'cyan');
  ALTER TABLE "_pages_v_blocks_cta_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::"public"."enum__pages_v_blocks_cta_cards_color";
  ALTER TABLE "_pages_v_blocks_cta_cards" ALTER COLUMN "color" SET DATA TYPE "public"."enum__pages_v_blocks_cta_cards_color" USING "color"::"public"."enum__pages_v_blocks_cta_cards_color";
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_variant";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_variant" AS ENUM('primary', 'secondary', 'background', 'highlight');
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE "public"."enum__pages_v_blocks_cta_variant" USING "variant"::"public"."enum__pages_v_blocks_cta_variant";
  ALTER TABLE "_pages_v_blocks_card_block_cards" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_card_block_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::text;
  UPDATE "_pages_v_blocks_card_block_cards" SET "color" = 'purple' WHERE "color" NOT IN ('purple', 'coral', 'cyan');
  DROP TYPE "public"."enum__pages_v_blocks_card_block_cards_color";
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_cards_color" AS ENUM('purple', 'coral', 'cyan');
  ALTER TABLE "_pages_v_blocks_card_block_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::"public"."enum__pages_v_blocks_card_block_cards_color";
  ALTER TABLE "_pages_v_blocks_card_block_cards" ALTER COLUMN "color" SET DATA TYPE "public"."enum__pages_v_blocks_card_block_cards_color" USING "color"::"public"."enum__pages_v_blocks_card_block_cards_color";
  ALTER TABLE "_pages_v_blocks_divider" ALTER COLUMN "primary_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_divider" ALTER COLUMN "primary_color" SET DEFAULT 'default'::text;
  UPDATE "_pages_v_blocks_divider" SET "primary_color" = 'default' WHERE "primary_color" NOT IN ('default', 'purple', 'coral', 'cyan', 'green');
  DROP TYPE "public"."enum__pages_v_blocks_divider_primary_color";
  CREATE TYPE "public"."enum__pages_v_blocks_divider_primary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  ALTER TABLE "_pages_v_blocks_divider" ALTER COLUMN "primary_color" SET DEFAULT 'default'::"public"."enum__pages_v_blocks_divider_primary_color";
  ALTER TABLE "_pages_v_blocks_divider" ALTER COLUMN "primary_color" SET DATA TYPE "public"."enum__pages_v_blocks_divider_primary_color" USING "primary_color"::"public"."enum__pages_v_blocks_divider_primary_color";
  ALTER TABLE "_pages_v_blocks_divider" ALTER COLUMN "secondary_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_divider" ALTER COLUMN "secondary_color" SET DEFAULT 'default'::text;
  UPDATE "_pages_v_blocks_divider" SET "secondary_color" = 'default' WHERE "secondary_color" NOT IN ('default', 'purple', 'coral', 'cyan', 'green');
  DROP TYPE "public"."enum__pages_v_blocks_divider_secondary_color";
  CREATE TYPE "public"."enum__pages_v_blocks_divider_secondary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green');
  ALTER TABLE "_pages_v_blocks_divider" ALTER COLUMN "secondary_color" SET DEFAULT 'default'::"public"."enum__pages_v_blocks_divider_secondary_color";
  ALTER TABLE "_pages_v_blocks_divider" ALTER COLUMN "secondary_color" SET DATA TYPE "public"."enum__pages_v_blocks_divider_secondary_color" USING "secondary_color"::"public"."enum__pages_v_blocks_divider_secondary_color";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_bg_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_bg_color" SET DEFAULT 'base'::text;
  UPDATE "_pages_v" SET "version_hero_bg_color" = 'purple' WHERE "version_hero_bg_color" NOT IN ('base', 'purple', 'coral', 'cyan');
  DROP TYPE "public"."enum__pages_v_version_hero_bg_color";
  CREATE TYPE "public"."enum__pages_v_version_hero_bg_color" AS ENUM('base', 'purple', 'coral', 'cyan');
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_bg_color" SET DEFAULT 'base'::"public"."enum__pages_v_version_hero_bg_color";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_bg_color" SET DATA TYPE "public"."enum__pages_v_version_hero_bg_color" USING "version_hero_bg_color"::"public"."enum__pages_v_version_hero_bg_color";
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "type" "enum_pages_blocks_content_columns_type" DEFAULT 'text';
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "media_id" integer;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "decorator_enabled" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "decorator_vertical_color" "enum_pages_blocks_content_columns_decorator_vertical_color" DEFAULT 'coral';
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "decorator_horizontal_color" "enum_pages_blocks_content_columns_decorator_horizontal_color" DEFAULT 'purple';
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "type" "enum__pages_v_blocks_content_columns_type" DEFAULT 'text';
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "media_id" integer;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "decorator_enabled" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "decorator_vertical_color" "enum__pages_v_blocks_content_columns_decorator_vertical_color" DEFAULT 'coral';
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "decorator_horizontal_color" "enum__pages_v_blocks_content_columns_decorator_horizontal_color" DEFAULT 'purple';
  ALTER TABLE "posts" ADD COLUMN "show_motif" boolean DEFAULT true;
  ALTER TABLE "_posts_v" ADD COLUMN "version_show_motif" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_content_columns" ADD CONSTRAINT "pages_blocks_content_columns_media_id_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD CONSTRAINT "_pages_v_blocks_content_columns_media_id_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "pages_blocks_content_columns_media_idx" ON "pages_blocks_content_columns" USING btree ("media_id");
  CREATE INDEX "_pages_v_blocks_content_columns_media_idx" ON "_pages_v_blocks_content_columns" USING btree ("media_id");
  ALTER TABLE "pages_blocks_content" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "eyebrow";
  ALTER TABLE "pages_blocks_card_block" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_carousel_logo_block" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_image_content" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_static_map" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_divider" DROP COLUMN "tertiary_color";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "eyebrow";
  ALTER TABLE "_pages_v_blocks_card_block" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_image_content" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_static_map" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_divider" DROP COLUMN "tertiary_color";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "title";
  DROP TYPE "public"."enum_pages_blocks_divider_tertiary_color";
  DROP TYPE "public"."enum__pages_v_blocks_divider_tertiary_color";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_divider_tertiary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green', 'pink', 'amber', 'white', 'ink');
  CREATE TYPE "public"."enum__pages_v_blocks_divider_tertiary_color" AS ENUM('default', 'purple', 'coral', 'cyan', 'green', 'pink', 'amber', 'white', 'ink');
  ALTER TYPE "public"."enum_pages_hero_slides_color" ADD VALUE 'green' BEFORE 'coral';
  ALTER TYPE "public"."enum_pages_blocks_divider_primary_color" ADD VALUE 'pink';
  ALTER TYPE "public"."enum_pages_blocks_divider_primary_color" ADD VALUE 'amber';
  ALTER TYPE "public"."enum_pages_blocks_divider_primary_color" ADD VALUE 'white';
  ALTER TYPE "public"."enum_pages_blocks_divider_primary_color" ADD VALUE 'ink';
  ALTER TYPE "public"."enum_pages_blocks_divider_secondary_color" ADD VALUE 'pink';
  ALTER TYPE "public"."enum_pages_blocks_divider_secondary_color" ADD VALUE 'amber';
  ALTER TYPE "public"."enum_pages_blocks_divider_secondary_color" ADD VALUE 'white';
  ALTER TYPE "public"."enum_pages_blocks_divider_secondary_color" ADD VALUE 'ink';
  ALTER TYPE "public"."enum_pages_hero_bg_color" ADD VALUE 'green' BEFORE 'coral';
  ALTER TYPE "public"."enum__pages_v_version_hero_slides_color" ADD VALUE 'green' BEFORE 'coral';
  ALTER TYPE "public"."enum__pages_v_blocks_divider_primary_color" ADD VALUE 'pink';
  ALTER TYPE "public"."enum__pages_v_blocks_divider_primary_color" ADD VALUE 'amber';
  ALTER TYPE "public"."enum__pages_v_blocks_divider_primary_color" ADD VALUE 'white';
  ALTER TYPE "public"."enum__pages_v_blocks_divider_primary_color" ADD VALUE 'ink';
  ALTER TYPE "public"."enum__pages_v_blocks_divider_secondary_color" ADD VALUE 'pink';
  ALTER TYPE "public"."enum__pages_v_blocks_divider_secondary_color" ADD VALUE 'amber';
  ALTER TYPE "public"."enum__pages_v_blocks_divider_secondary_color" ADD VALUE 'white';
  ALTER TYPE "public"."enum__pages_v_blocks_divider_secondary_color" ADD VALUE 'ink';
  ALTER TYPE "public"."enum__pages_v_version_hero_bg_color" ADD VALUE 'green' BEFORE 'coral';
  ALTER TABLE "pages_blocks_content_columns" DROP CONSTRAINT "pages_blocks_content_columns_media_id_media_id_fk";
  
  ALTER TABLE "_pages_v_blocks_content_columns" DROP CONSTRAINT "_pages_v_blocks_content_columns_media_id_media_id_fk";
  
  ALTER TABLE "pages_blocks_cta_cards" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_cards_color";
  CREATE TYPE "public"."enum_pages_blocks_cta_cards_color" AS ENUM('coral', 'purple', 'cyan', 'green');
  ALTER TABLE "pages_blocks_cta_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::"public"."enum_pages_blocks_cta_cards_color";
  ALTER TABLE "pages_blocks_cta_cards" ALTER COLUMN "color" SET DATA TYPE "public"."enum_pages_blocks_cta_cards_color" USING "color"::"public"."enum_pages_blocks_cta_cards_color";
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_cta_variant";
  CREATE TYPE "public"."enum_pages_blocks_cta_variant" AS ENUM('primary', 'secondary', 'background', 'highlightLeft', 'highlightCentered');
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE "public"."enum_pages_blocks_cta_variant" USING "variant"::"public"."enum_pages_blocks_cta_variant";
  ALTER TABLE "pages_blocks_card_block_cards" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_card_block_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::text;
  DROP TYPE "public"."enum_pages_blocks_card_block_cards_color";
  CREATE TYPE "public"."enum_pages_blocks_card_block_cards_color" AS ENUM('coral', 'purple', 'cyan', 'green');
  ALTER TABLE "pages_blocks_card_block_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::"public"."enum_pages_blocks_card_block_cards_color";
  ALTER TABLE "pages_blocks_card_block_cards" ALTER COLUMN "color" SET DATA TYPE "public"."enum_pages_blocks_card_block_cards_color" USING "color"::"public"."enum_pages_blocks_card_block_cards_color";
  ALTER TABLE "_pages_v_blocks_cta_cards" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_cards_color";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_cards_color" AS ENUM('coral', 'purple', 'cyan', 'green');
  ALTER TABLE "_pages_v_blocks_cta_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::"public"."enum__pages_v_blocks_cta_cards_color";
  ALTER TABLE "_pages_v_blocks_cta_cards" ALTER COLUMN "color" SET DATA TYPE "public"."enum__pages_v_blocks_cta_cards_color" USING "color"::"public"."enum__pages_v_blocks_cta_cards_color";
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_variant";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_variant" AS ENUM('primary', 'secondary', 'background', 'highlightLeft', 'highlightCentered');
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "variant" SET DATA TYPE "public"."enum__pages_v_blocks_cta_variant" USING "variant"::"public"."enum__pages_v_blocks_cta_variant";
  ALTER TABLE "_pages_v_blocks_card_block_cards" ALTER COLUMN "color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_card_block_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::text;
  DROP TYPE "public"."enum__pages_v_blocks_card_block_cards_color";
  CREATE TYPE "public"."enum__pages_v_blocks_card_block_cards_color" AS ENUM('coral', 'purple', 'cyan', 'green');
  ALTER TABLE "_pages_v_blocks_card_block_cards" ALTER COLUMN "color" SET DEFAULT 'coral'::"public"."enum__pages_v_blocks_card_block_cards_color";
  ALTER TABLE "_pages_v_blocks_card_block_cards" ALTER COLUMN "color" SET DATA TYPE "public"."enum__pages_v_blocks_card_block_cards_color" USING "color"::"public"."enum__pages_v_blocks_card_block_cards_color";
  DROP INDEX "pages_blocks_content_columns_media_idx";
  DROP INDEX "_pages_v_blocks_content_columns_media_idx";
  ALTER TABLE "pages_blocks_content" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "pages_blocks_card_block" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_carousel_logo_block" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_image_content" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_static_map" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_divider" ADD COLUMN "tertiary_color" "enum_pages_blocks_divider_tertiary_color" DEFAULT 'default';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "_pages_v_blocks_card_block" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_carousel_logo_block" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_image_content" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_static_map" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_divider" ADD COLUMN "tertiary_color" "enum__pages_v_blocks_divider_tertiary_color" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "type";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "media_id";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "decorator_enabled";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "decorator_vertical_color";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "decorator_horizontal_color";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "type";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "media_id";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "decorator_enabled";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "decorator_vertical_color";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "decorator_horizontal_color";
  ALTER TABLE "posts" DROP COLUMN "show_motif";
  ALTER TABLE "_posts_v" DROP COLUMN "version_show_motif";
  DROP TYPE "public"."enum_pages_blocks_content_columns_type";
  DROP TYPE "public"."enum_pages_blocks_content_columns_decorator_vertical_color";
  DROP TYPE "public"."enum_pages_blocks_content_columns_decorator_horizontal_color";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_type";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_decorator_vertical_color";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_decorator_horizontal_color";`)
}
